# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63beb95638184192d8db7ae794ec2775c24185cda55dbaf0f321b50020359919870f2370be8c9067e91a0070225ac5795b43ff9d45c49f39b101a2235278f646

test:
  secret_key_base: dc5d48927a8d0ef7e6cf8dd1db3390057b6c9e09ae26055baea5469212cacd645618570fb8ca626d0bb13f98b8c9f68a4751eafd11020135f1950af9ef7eefcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
